# Generated by Django 4.2.2 on 2023-06-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hit',
            field=models.IntegerField(null=True),
        ),
    ]
