# Generated by Django 4.2.2 on 2023-06-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoulEstateReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('접수연도', models.IntegerField(blank=True, null=True)),
                ('자치구코드', models.IntegerField(blank=True, null=True)),
                ('자치구명', models.CharField(max_length=30)),
                ('법정동코드', models.IntegerField(blank=True, null=True)),
                ('법정동명', models.CharField(max_length=40)),
                ('본번', models.IntegerField(blank=True, null=True)),
                ('부번', models.IntegerField(blank=True, null=True)),
                ('건물명', models.CharField(max_length=200)),
                ('계약일', models.CharField(blank=True, max_length=20, null=True)),
                ('물건금액_만원', models.IntegerField(blank=True, null=True)),
                ('건물면적', models.CharField(max_length=30)),
                ('토지면적', models.CharField(max_length=30)),
                ('층', models.CharField(max_length=10)),
                ('권리구분', models.CharField(blank=True, max_length=25, null=True)),
                ('취소일', models.CharField(blank=True, max_length=20, null=True)),
                ('건축년도', models.CharField(max_length=20)),
                ('건물용도', models.CharField(max_length=50)),
                ('신고구분', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeoulEstateRealLonLat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('주소', models.CharField(max_length=400)),
                ('위도', models.CharField(max_length=300)),
                ('경도', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SeoulEstateRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('접수연도', models.IntegerField(blank=True, null=True)),
                ('자치구코드', models.IntegerField(blank=True, null=True)),
                ('자치구명', models.CharField(max_length=30)),
                ('법정동코드', models.IntegerField(blank=True, null=True)),
                ('법정동명', models.CharField(max_length=40)),
                ('본번', models.IntegerField(blank=True, null=True)),
                ('부번', models.IntegerField(blank=True, null=True)),
                ('층', models.CharField(max_length=10)),
                ('계약일', models.CharField(blank=True, max_length=20, null=True)),
                ('전월세구분', models.CharField(blank=True, max_length=30, null=True)),
                ('임대면적', models.CharField(max_length=30)),
                ('보증금_만원', models.IntegerField(blank=True, null=True)),
                ('임대료_만원', models.IntegerField(blank=True, null=True)),
                ('건물명', models.CharField(max_length=200)),
                ('건축년도', models.CharField(max_length=20)),
                ('건물용도', models.CharField(max_length=50)),
                ('계약기간', models.CharField(blank=True, max_length=100, null=True)),
                ('신규갱신여부', models.CharField(blank=True, max_length=20, null=True)),
                ('종전보증금_만원', models.IntegerField(blank=True, null=True)),
                ('종전임대료_만원', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeoulEstateRentLonLat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('주소', models.CharField(max_length=400)),
                ('위도', models.CharField(max_length=300)),
                ('경도', models.CharField(max_length=300)),
            ],
        ),
    ]
