# Generated by Django 4.2.2 on 2023-06-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_seoulestatereal_seoulestatereallonlat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seoul2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('접수연도', models.IntegerField(blank=True, null=True)),
                ('자치구코드', models.IntegerField(blank=True, null=True)),
                ('자치구명', models.CharField(max_length=30)),
                ('법정동코드', models.IntegerField(blank=True, null=True)),
                ('법정동명', models.CharField(max_length=40)),
                ('본번', models.IntegerField(blank=True, null=True)),
                ('부번', models.IntegerField(blank=True, null=True)),
                ('층', models.CharField(max_length=10)),
                ('계약일', models.CharField(blank=True, max_length=20, null=True)),
                ('전월세구분', models.CharField(blank=True, max_length=30, null=True)),
                ('임대면적', models.CharField(max_length=30)),
                ('보증금_만원', models.IntegerField(blank=True, null=True)),
                ('임대료_만원', models.IntegerField(blank=True, null=True)),
                ('건물명', models.CharField(max_length=200, null=True)),
                ('건축년도', models.CharField(max_length=20, null=True)),
                ('건물용도', models.CharField(max_length=50, null=True)),
                ('계약기간', models.CharField(blank=True, max_length=100, null=True)),
                ('신규갱신여부', models.CharField(blank=True, max_length=20, null=True)),
                ('계약갱신권사용여부', models.CharField(max_length=20, null=True)),
                ('종전보증금', models.IntegerField(blank=True, null=True)),
                ('종전임대료', models.IntegerField(blank=True, null=True)),
                ('위도', models.CharField(max_length=300, null=True)),
                ('경도', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SeoulEstateReal',
        ),
        migrations.DeleteModel(
            name='SeoulEstateRent',
        ),
    ]
