# Generated by Django 4.2.2 on 2023-06-26 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_seoul2_delete_seoulestatereal_delete_seoulestaterent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seoul2',
        ),
        migrations.DeleteModel(
            name='SeoulEstateRealLonLat',
        ),
        migrations.DeleteModel(
            name='SeoulEstateRentLonLat',
        ),
    ]
