# Generated by Django 4.2.2 on 2023-06-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_delete_seoul2_delete_seoulestatereallonlat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='seoul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=50)),
                ('gucd', models.IntegerField(blank=True)),
                ('gunm', models.CharField(blank=True, max_length=50)),
                ('dongcd', models.IntegerField(blank=True)),
                ('dongnm', models.CharField(blank=True, max_length=50)),
                ('distin', models.CharField(blank=True, max_length=30)),
                ('bn', models.IntegerField(blank=True)),
                ('sbn', models.IntegerField(blank=True)),
                ('fl', models.IntegerField(blank=True)),
                ('cont', models.CharField(blank=True, max_length=200)),
                ('distin2', models.CharField(blank=True, max_length=50)),
                ('spa', models.CharField(blank=True, max_length=100)),
                ('depos', models.IntegerField(blank=True)),
                ('depos2', models.IntegerField(blank=True)),
                ('bdnm', models.TextField(blank=True)),
                ('bdcont', models.IntegerField(blank=True)),
                ('bdusa', models.CharField(blank=True, max_length=50)),
                ('cont2', models.CharField(blank=True, max_length=500)),
                ('newcont', models.CharField(blank=True, max_length=50)),
                ('mewcont2', models.CharField(blank=True, max_length=20)),
                ('olddepos', models.IntegerField(blank=True, null=True)),
                ('olddepos2', models.IntegerField(blank=True, null=True)),
                ('lat', models.CharField(blank=True, max_length=300)),
                ('lng', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'seoul',
            },
        ),
    ]
