# Generated by Django 4.2.2 on 2023-06-26 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_seoul'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='seoul',
            new_name='Seoulestate',
        ),
        migrations.AlterModelTable(
            name='seoulestate',
            table='seoulestate',
        ),
    ]
