# Generated by Django 4.2.2 on 2023-06-26 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_alter_seoulestate_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seoulestate',
            old_name='mewcont2',
            new_name='newcont2',
        ),
    ]
