# Generated by Django 4.2.2 on 2023-06-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_rename_mewcont2_seoulestate_newcont2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoulestate',
            name='bdcont',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='seoulestate',
            name='bn',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='seoulestate',
            name='depos',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='seoulestate',
            name='depos2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='seoulestate',
            name='dongcd',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='seoulestate',
            name='fl',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='seoulestate',
            name='gucd',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='seoulestate',
            name='olddepos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='seoulestate',
            name='olddepos2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='seoulestate',
            name='sbn',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
