# Generated by Django 4.2.2 on 2023-06-28 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0013_seoulestate2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seoulestate',
            new_name='SeouljRent',
        ),
        migrations.RenameModel(
            old_name='Seoulestate2',
            new_name='SeoulReal',
        ),
        migrations.AlterModelTable(
            name='seouljrent',
            table='SeouljRent',
        ),
        migrations.AlterModelTable(
            name='seoulreal',
            table='SeoulReal',
        ),
    ]
